//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AadimPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area_details
    {
        public int id { get; set; }
        public Nullable<int> fourWheel_capacity { get; set; }
        public Nullable<int> twoWheel_capacity { get; set; }
        public Nullable<int> fourWheel_occupied { get; set; }
        public Nullable<int> twoWheel_occupied { get; set; }
        public Nullable<int> Area_id { get; set; }
        public Nullable<int> two_price { get; set; }
        public Nullable<int> four_price { get; set; }
    
        public virtual Area Area { get; set; }
    }
}
