//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AadimPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int id { get; set; }
        public string type { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<int> entry_id { get; set; }
        public Nullable<int> booking_id { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual entry entry { get; set; }
    }
}
