//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AadimPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booking()
        {
            this.entries = new HashSet<entry>();
            this.bills = new HashSet<bill>();
        }
    
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public string Vechical_number { get; set; }
        public Nullable<int> Time_table_id { get; set; }
        public Nullable<int> Area_id { get; set; }
        public string vechical_type { get; set; }
        public string paid { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Time_table Time_table { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entry> entries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bills { get; set; }
    }
}
