//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AadimPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancled_booking
    {
        public int id { get; set; }
        public Nullable<int> time_table_id { get; set; }
        public Nullable<int> userId { get; set; }
        public string vechical_number { get; set; }
    }
}
