//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AadimPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public entry()
        {
            this.bills = new HashSet<bill>();
        }
    
        public int id { get; set; }
        public Nullable<int> booking_id { get; set; }
        public Nullable<System.TimeSpan> entry_time { get; set; }
        public Nullable<System.TimeSpan> exit_time { get; set; }
        public string Vechical_number { get; set; }
        public string Vechical_type { get; set; }
        public string Status { get; set; }
        public Nullable<int> Area_id { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bills { get; set; }
    }
}
